# Generated by Django 5.2.8 on 2025-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_remove_universitycourse_unique_question_and_order_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='university',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_university_name_country'),
        ),
    ]
