# Generated by Django 5.2.8 on 2025-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_unique_university_name_country'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_course_title_name'),
        ),
    ]
