# Generated by Django 5.2.8 on 2025-11-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_course_unique_course_title_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.course'),
        ),
        migrations.AlterField(
            model_name='universitycourse',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university'),
        ),
    ]
